times= ('Botafogo','Palmeiras','Bragantino','Grêmio','Flamengo','Atlético-Mineiro','Athletico-PR','Fluminense','São Paulo','Buiabá','Fortaleza','Internacional','Corinthians','Santos','Bahia','Vasco da Gama','Cruzeiro','Goiás','Coritiba','América-MG')
print('=='*50)
print(f'Os 5 primeiros são {times[:5]}')
print('=='*50)
print(f'Os 4 últimos são {times[-4:]}')
print('=='*50)
print(f'Times em ordem alfabética {sorted(times)}.')
print('=='*50)
print(f'A Flamengo esta na posição {times.index("Flamengo")+1}')